version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend/index.html:/frontend/index.html
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/app.py:/backend/app.py
